modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL="${issues}"
license="${license}"
showAsResourcePack=false
[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${name}"
displayURL="${homepage}"
logoFile="icon.png"
authors="${authors}"
description="${description}"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="curios"
type="optional"
versionRange="${curios_range}"
ordering="BEFORE"
side="BOTH"

[[mixins]]
config = "spyglass_improvements.common.mixins.json"
[[mixins]]
config = "spyglass_improvements.neoforge.mixins.json"