
name: Publish Spylgass Improvements to CurseForge and Modrinth

on: [ workflow_dispatch ]

env:
  MINECRAFT_VERSION: '[1.20.2,1.21)'
  JAVA_VERSION: 17
  VERSION: 1.5+mc1.20.2+forge
  RELEASE_NAME: '[1.20.2 Forge] Spyglass Improvements 1.5'
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 571264
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: Z6ykjRlM
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          modrinth-featured: true

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md
          dependencies: |
            curios(optional)

          loaders: forge
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
